# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1804"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.define "build-server" do |v|
    v.vm.hostname = "build"
    v.vm.network :private_network, ip: "192.168.43.41"
  end

  config.vm.define "prod-server" do |v|
    v.vm.hostname = "prod-server"
    v.vm.network :private_network, ip: "192.168.43.40"
  end
end
